### ISSUE TITLE
How to change JsonSerializerSettings?

### ISSUE THREAD

**Issue by gregorvilkner** [alexdrenea/CosmosDb.Net#4]
How do I set or check the JsonSerializerSettings? I struggle with UTC timestamp strings getting wrongly parsed and converted to local time. I'm looking for either DateParseHandling.None or DateTimeZoneHandling.Utc. Any advice would be appreciated. Cheers, Gregor

**Comment by alexdrenea** [comment]
At this point there is no way to customize the JsonSeralizerSettings (considering to add this in a new release).
However, you might be able to use the `JsonConvert.DefaultSettings` to set this globally in your app?

**Comment by gregorvilkner** [comment]
Thanks. I'll take a look into that.
